<html>
    <head>
        <title>Martina Hübner-Zehnle Systemische Therapie und Beratung</title>

        <link href="css/bootstrap-theme.min.css" rel="stylesheet" type="text/css"/>
        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="css/pagelayout.css" rel="stylesheet" type="text/css"/> 
        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>
    <body>

            <nav class="navbar-static-top header">
                <div class="container">
                    <div class="navbar-header navbar-left">
                        <h1>Martina H&uuml;bner-Zehnle</h1>
                        <span class="green">Systemische Therapie</span>&nbsp;<span> und Beratung</span> 
                    </div>
                    <div class="nav navbar-right">
                        <img src="img/Logo1_2.png" alt=""/>
                    </div>
                </div>
            </nav>
        <div id="wrap">
            <div class="container">
                <ul class="nav nav-pills">    
                    <li class="active"><a href="www.google.de">Home</a></li>                          
                    <li><a href="ueber-mich.phtml">&Uuml;ber mich</a></li>
                    <li><a href="www.google.de">T&auml;tigkeiten</a></li>
                    <li><a href="www.google.de">News</a></li>
                    <li><a href="kontakt.phtml">Kontakt</a></li>
                </ul>
            </div>
            <div class="container">
                <div class="row start-text">
                    <div class="col-md-4">

                                             
                    </div>
                    <div class="col-md-8">
                        <h2>Über mich</h2>
                        <p>Geboren bin ich 1961. Meine berufliche Laufbahn begann 1981 mit dem  Studium der Sozialarbeit in Freiburg. In regelmäßigen Kursen und Workshops  und im fachlichen Austausch mit Kollegen und Supervisoren bilde ich mich stetig fachlich fort. 2009 absolvierte ich eine therapeutische  Ausbildung als systemische Beraterin und Therapeutin. Bei der Deutschen Gesellschaft für Systemische Therapie, Beratung und Familientherapie (DGSF) bin ich zertifiziert. Als Soziotherapeutin bei den Krankenkassen bin ich anerkannt.</p>
                        <p>Der Hauptschwerpunkt meiner beruflichen Tätigkeit liegt in der Krisenintervention für Menschen, die unter psychischen Belastungen leiden. Neben der systemisch-therapeutischen Arbeit unterstütze ich meine Klienten im Antragsverfahren bei den Sozialversicherungsträgern und Sozialbehörden. </p>
                        <p>Seit mehreren Jahren bin ich freiberuflich als systemische Einzel- Paar und Familientherapeutin in eigener Praxis oder in Honorartätigkeit für verschiedene Anbieter im sozialen Bereich tätig.</p>
                        <p>Neben meiner beruflichen Tätigkeit engagiere ich mich ehrenamtlich in verschiedenen Gremien.</p>
                        <p>Ich bin verheiratet und habe zwei (fast) erwachsene Töchter.</p>
                    </div>
                    
                    <strong><u>Qualifikationen und Erfahrungen:</u></strong>
                    <ul>
                        <li>Studium der Sozialarbeit in Freiburg</li>
                        <li>Ausbildung als systemische Beraterin und Therapeutin.</li>
                        <li>Zertifiziert bei der Deutschen Gesellschaft für Systemische Therapie, Beratung und Familientherapie (DGSF)</li>
                        <li>Mitarbeiterin bei Systheb</li>
                    </ul>
                </div>
                <div id="push"></div>
            </div>
            <div class="footer">
                <div class="container">
                    <div class="col-md-12">
                      <a href="tel: +497222651498">07222 / 651498</a> - <a href="mailto:m.huebner-zehnle@t-online.de">m.huebner-zehnle@t-online.de</a> - Dörnigstrasse 6 - 76571 Gaggenau
                    </div>
                    
                </div>
            </div>
    </body>
</html>